version: '3.8'

services:
  mariadb:
    image: 'mariadb:10.6'
    hostname: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - data-lakehouse-network

  hive-metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083'
    volumes:
      - ./metastore_conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - data-lakehouse-network

  trino:
    image: trinodb/trino:410
    hostname: trino
    ports:
      - '8080:8080'
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    depends_on:
      - minio
      - hive-metastore
    networks:
      - data-lakehouse-network

  minio:
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: test12334567
    command: server /data --console-address ":9001"
    networks:
      - data-lakehouse-network

  metabase:
    image: metabase/metabase:v0.45.3
    hostname: metabase
    ports:
      - '3000:3000'
    volumes:
      - ./metabase/plugins:/plugins
      - ./metabase/data:/metabase-data
    environment:
      MB_PLUGINS_DIR: /plugins
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - trino
    networks:
      - data-lakehouse-network

networks:
  data-lakehouse-network:
    name: data-lakehouse-network
    driver: bridge